// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfOsv_F9JsEnTfZscaQgwhX2maX6anpZ8',
    appId: '1:528436156653:web:ab82359ece080d270dd4e4',
    messagingSenderId: '528436156653',
    projectId: 'easyta3lim',
    authDomain: 'easyta3lim.firebaseapp.com',
    storageBucket: 'easyta3lim.firebasestorage.app',
    measurementId: 'G-E7ZD1VXS4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSVSLsq-dTv4XYkzS-KHIV2X8BVLgHDM0',
    appId: '1:528436156653:android:f148f51c2d142ef50dd4e4',
    messagingSenderId: '528436156653',
    projectId: 'easyta3lim',
    storageBucket: 'easyta3lim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7xIHC-m4rysgJFciLlDEIaaMjO9q4zsM',
    appId: '1:528436156653:ios:147daeb8a1185b610dd4e4',
    messagingSenderId: '528436156653',
    projectId: 'easyta3lim',
    storageBucket: 'easyta3lim.firebasestorage.app',
    iosBundleId: 'com.example.academyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7xIHC-m4rysgJFciLlDEIaaMjO9q4zsM',
    appId: '1:528436156653:ios:147daeb8a1185b610dd4e4',
    messagingSenderId: '528436156653',
    projectId: 'easyta3lim',
    storageBucket: 'easyta3lim.firebasestorage.app',
    iosBundleId: 'com.example.academyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfOsv_F9JsEnTfZscaQgwhX2maX6anpZ8',
    appId: '1:528436156653:web:cbf1d16a61855c1f0dd4e4',
    messagingSenderId: '528436156653',
    projectId: 'easyta3lim',
    authDomain: 'easyta3lim.firebaseapp.com',
    storageBucket: 'easyta3lim.firebasestorage.app',
    measurementId: 'G-ZJTEV1KR2P',
  );
}
